id: 2fg7
name: OnRobot 2FG7
driver: fg7.FG7
nodes:
  gripper:
    properties:
      width:
        datatype: float
        unit: mm
        settable: true
        min: 0
        max: 140
      force:
        datatype: float
        unit: N
        settable: true
        min: 0
        max: 40
      speed:
        datatype: int
        unit: '%'
        settable: true
        min: 10
        max: 100
      busy:
        datatype: bool
        settable: false
      grip_detected:
        datatype: bool
        settable: false
      not_calibrated:
        datatype: bool
        settable: false
