id: 3fg15
name: OnRobot 3FG15
driver: fg15.FG15
nodes:
  gripper:
    properties:
      diameter_external:
        datatype: float
        unit: mm
        settable: true
        min: 4
        max: 152
      diameter_internal:
        datatype: float
        unit: mm
        settable: true
        min: 35
        max: 181
      force:
        datatype: float
        unit: '%'
        settable: true
        min: 0
        max: 100
      busy:
        datatype: bool
        settable: false
      grip_detected:
        datatype: bool
        settable: false
      force_grip_detected:
        datatype: bool
        settable: false
      calibration_ok:
        datatype: bool
        settable: false