id: rg6
name: OnRobot RG6
driver: rg2_rg6.RG
gripper_arg: rg6
nodes:
  gripper:
    properties:
      width:
        datatype: float
        unit: mm
        settable: true
        min: 0
        max: 160
      force:
        datatype: float
        unit: N
        settable: true
        min: 0
        max: 120
      busy:
        datatype: bool
        settable: false
      grip_detected:
        datatype: bool
        settable: false
      safety_error:
        datatype: bool
        settable: false