id: sg
name: OnRobot SG
driver: sg.SG
nodes:
  gripper:
    properties:
      width:
        datatype: float
        unit: mm
        settable: true
        min: 0
        max: 110
      gentle_grip:
        datatype: bool
        settable: true
      busy:
        datatype: bool
        settable: false
      initialized:
        datatype: bool
        settable: false
      error:
        datatype: bool
        settable: false