id: vg10
name: OnRobot VG10
driver: vg10.VG10
nodes:
  gripper:
    properties:
      vacuum_channel_a:
        datatype: float
        unit: '%'
        settable: true
        min: 0
        max: 80
      vacuum_channel_b:
        datatype: float
        unit: '%'
        settable: true
        min: 0
        max: 80
      actual_vacuum_a:
        datatype: float
        unit: relative vacuum
        settable: false
      actual_vacuum_b:
        datatype: float
        unit: relative vacuum
        settable: false

